### PR TITLE
[iOS only] Feat: Add the way to customize iOS cropper toolbar

### PR DESCRIPTION
**Pull request by anton-patrushev**
### What's new
This PR adds a way to customize iOS cropper toolbar using custom (HEX only) colors for the toolbar buttons (`Choose` and `Cancel`).

### Demo
If I would pass custom colors to `openCropper` or `openPicker` it would apply provided colors
`openCropper` example:
```ts
async function launchCropper() {
  const imageUri: string = await SomeImageUtils.openPicker();

  return await ImageCropper.openCropper({
    path: imageUri,
    mediaType: 'photo',
    cropperChooseColor: '#00E78A',
    cropperCancelColor: '#FFFFFF',
  });
}
```
or `openPicker` example:
```ts
async function launchPicker() {
  return await ImageCropper.openPicker({
    cropperChooseColor: '#00E78A',
    cropperCancelColor: '#FFFFFF',
  });
}
```
Simulator Screenshot - iPhone 14 Pro Max - 2023-05-12 at 10 56 53

And if I would not pass any custom colors it would fallback to default values
`openCropper` example:
```ts
async function launchCropper() {
  const imageUri: string = await SomeImageUtils.openPicker();

  return await ImageCropper.openCropper({
    path: imageUri,
    mediaType: 'photo'
  });
}
```
or `openPicker` example:
```ts
async function launchPicker() {
  return await ImageCropper.openPicker();
}
```
Simulator Screenshot - iPhone 14 Pro Max - 2023-05-12 at 10 55 09

### How it was tested
It was manually QA in iOS Simulator (iOS 15 and iOS 16)

### CODE REVIEW

**Review by TMatuszewski — APPROVED** [review]

**Comment by anton-patrushev** [comment]
@ivpusic can you take a look please?

**Comment by ivpusic** [comment]
tnx for PR! could you update readme file with new options?

**Comment by anton-patrushev** [comment]
@ivpusic
README file was updated here 2dca3e3d5ba7f72119895df59fd679b3412d00d9

Can you approve this PR and release a new version, please?

**Comment by anton-patrushev** [comment]
Would you make a new release cut (`0.40.0` or `0.39.1` or even `1.0.0`)? @ivpusic

**Comment by Blackfaded** [comment]
I would also love a new version on npm.
Was a little bit confused why the colors did not apply in my app, because the docs are updated to 0.40.0, but the package on npm is still 0.39.

Btw: Thanks for this awesome lib!

**Comment by ivpusic** [comment]
0.40.0 released to npm

**Pull request merged**
