### PR TITLE
Added option to set free style crop for android.

### PR DESCRIPTION
**Pull request by NikolaRavic**
As uCrop (on which this lib relies for Android) supports this feature I thought it would be very nice feature to have this.

### CODE REVIEW

**Comment by ivpusic** [comment]
could you also update readme file?

**Comment by NikolaRavic** [comment]
Yes of course. In a moment ;)

**Comment by ivpusic** [comment]
thanks!

**Comment by NikolaRavic** [comment]
Thanks! That was fast

**Comment by NikolaRavic** [comment]
Maybe just bump the version in package.json and publish new npm package so I can use new option.

**Pull request merged**
