### PR TITLE
Proposal to replace RSKImageCropper with TOCropViewController

### PR DESCRIPTION
**Pull request by sergioutama**
This proposal is to address limitation when cropping image on iOS using RSKImageCropper such as support for rotation (#787) and custom/free defined rectangle.

TOCropViewController was chosen because it has similar feature that available on android (yalantis/ucrop). The implementation of it also very similar with `RSKImageCropper`.

I believe there are more things to do before RSKImageCropper can be totally replaced with TOCropViewController, so if you agree with this proposal, I'll make it done.

### CODE REVIEW

**Comment by ivpusic** [comment]
TOCropViewController looks good. However, we should not make any regressions in terms of feature set in comparison with RSKImageCropper. If you think all features are there (check croppings options here https://github.com/ivpusic/react-native-image-crop-picker#request-object), then I would gladly accept PR.

**Comment by sergioutama** [comment]
@ivpusic there is no changes on support for https://github.com/ivpusic/react-native-image-crop-picker#request-object all object is supported as it is.

Here are the list of changes that you might need to be aware of

| Feature | RSKImageCropper | TOCropViewController |
|---|---|---|
| request object | Supported | Supported |
| circular crop | Supported | Supported |
| rectangular crop | Supported (with fix crop area) | Supported (flexible crop area) |
| image rotation | Not Supported | Supported |
| UI for control  | None | Masked Crop Area, Grid overlay, Rotation, Undo Changes |

The only drawback for now is: it will force user to use Cocoapods, however as far as i see this library also have issue with manual linking or even `react-native link` which is different matter all together.

I will do few more test on my end and i hope you can also test it on your end in case you have other concern.

**Comment by paolospag** [comment]
Any update on this?
A flexible crop area in iOS would be awesome!

**Comment by sergioutama** [comment]
@paolospag temporarily you can just use the forked version on my repo, i haven't had a chance to fix dependency on cocoapods. My changes require the usage of Cocoapods.

https://github.com/sergioutama/react-native-image-crop-picker

**Comment by SL-A-SH** [comment]
Any updates on this? Or should I use your forked version @sergioutama ?

**Comment by SL-A-SH** [comment]
@sergioutama I am using your forked version in my project however the quality of the image after cropping is degraded a lot, like really bad. Since your repository does not accept issues, I had to write here.

**Comment by sergioutama** [comment]
@SL-A-SH i was a overwhelmed with work lately
Your issue is actually related with #825 #843 and i have't had a chance to fix it for now.
Basically the crop applied multiple times

There is an workaround for now (which i use as well)

1. Detect if the platform is iOS
2. If the platform is iOS set the `width` and `height` of the crop to be at least 2x of android (i personally make it 3x the size of android, you can find which one suitable for you)

eg
```
const data = await camera.takePictureAsync(options);
const croppedImage = await ImagePicker.openCropper({
          path: data.uri,
          width: (Platform.OS ==='ios')? 200 : 100,
          height: (Platform.OS ==='ios')? 200 : 100,
          freeStyleCropEnabled: true,
          showCropGuidelines: true,
          compressImageQuality: 0.7
        });
```

**Comment by alexpchin** [comment]
Hi all, is this going to be picked up?

**Comment by afeichuanqi** [comment]
> @paolospag temporarily you can just use the forked version on my repo, i haven't had a chance to fix dependency on cocoapods. My changes require the usage of Cocoapods.
> 
> https://github.com/sergioutama/react-native-image-crop-picker

Is there time to make a version that supports 0.6?

**Comment by afeichuanqi** [comment]
> @SL-A-SH i was a overwhelmed with work lately
> Your issue is actually related with #825 #843 and i have't had a chance to fix it for now.
> Basically the crop applied multiple times
> 
> There is an workaround for now (which i use as well)
> 
> 1. Detect if the platform is iOS
> 2. If the platform is iOS set the `width` and `height` of the crop to be at least 2x of android (i personally make it 3x the size of android, you can find which one suitable for you)
> 
> eg
> 
> ```
> const data = await camera.takePictureAsync(options);
> const croppedImage = await ImagePicker.openCropper({
>           path: data.uri,
>           width: (Platform.OS ==='ios')? 200 : 100,
>           height: (Platform.OS ==='ios')? 200 : 100,
>           freeStyleCropEnabled: true,
>           showCropGuidelines: true,
>           compressImageQuality: 0.7
>         });
> ```

When I use your plugin, I find that when I enter the trim bar from the album, click Cancel and a modal is not closed.
This is a native modal. I can't close it through react-native. Can I fix it?

**Comment by sergioutama** [comment]
@afeichuanqi feel free to do so :)

**Comment by afeichuanqi** [comment]
> @afeichuanqi feel free to do so :)

Because a lot of people use this version you have modified.
Hope that this bug can be resolved

**Comment by sergioutama** [comment]
@afeichuanqi thanks that give me encouragement to work on this library once again

**Comment by afeichuanqi** [comment]
> @afeichuanqi thanks that give me encouragement to work on this library once again

Because of this version, I do n’t know why the tailoring of ios is so bad. I read a lot of issues and asked if I could change one. Then I found your findings and it ’s very good. And it ’s very similar to android. I ’ve already used your version but there are some bugs.

**Comment by sergioutama** [comment]
@afeichuanqi what's your bugs?
I recently sync with the main repo
can you try and let me know what's the bug so i can make PR for the bugs as well

**Comment by afeichuanqi** [comment]
> @afeichuanqi what's your bugs?
> I recently sync with the main repo
> can you try and let me know what's the bug so i can make PR for the bugs as well

2019-12-26 18:25:07.555509+0800 AwesomeProject[958:427017] [core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
2019-12-26 18:25:08.981 [warn][tid:com.facebook.react.ImageCropPickerQueue][RCTImageLoader.mm:963] Calling bridge.imageLoader is deprecated and will not work in newer versions of RN. Please update to themoduleForClass API or turboModuleLookupDelegate API.

**Comment by afeichuanqi** [comment]
> @afeichuanqi what's your bugs?
> I recently sync with the main repo
> can you try and let me know what's the bug so i can make PR for the bugs as well

[Assert] Cannot be called with asCopy = NO on non-main thread.

**Comment by sergioutama** [comment]
> 2019-12-26 18:25:07.555509+0800 AwesomeProject[958:427017] [core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
> 2019-12-26 18:25:08.981 [warn][tid:com.facebook.react.ImageCropPickerQueue][RCTImageLoader.mm:963] Calling bridge.imageLoader is deprecated and will not work in newer versions of RN. Please update to themoduleForClass API or turboModuleLookupDelegate API.

for this i believe already fixed.
Make sure you try the latest one from this fork
you might want to remove the old library and install it again to ensure the latest version

> [Assert] Cannot be called with asCopy = NO on non-main thread.

while this i can't replicate, most likely it's similar with above

**Comment by sergioutama** [comment]
@ivpusic hey man, it's been months :)
There is no issue on the regression at all for this library and i believe quite a number of people been using this fork without issue. Would love if you can consider this to be merged.

Something you might want to take note

I haven't remove the original `RSKImageCropper` library from the Podspec.
This is because I want this fork to be accepted first. The effect is only a slightly larger build artifact.
Once this fork merged to main repo, i will make another PR to completely remove the old dependency on `RSKImageCropper`

**Comment by afeichuanqi** [comment]
> @ivpusic hey man, it's been months :)
> There is no issue on the regression at all for this library and i believe quite a number of people been using this fork without issue. Would love if you can consider this to be merged.
> 
> Something you might want to take note
> 
> I haven't remove the original `RSKImageCropper` library from the Podspec.
> This is because I want this fork to be accepted first. The effect is only a slightly larger build artifact.
> Once this fork merged to main repo, i will make another PR to completely remove the old dependency on `RSKImageCropper`

Cannot be called with asCopy = NO on non-main thread. 这个问题我在你刚才更新的分叉依旧碰到了

**Comment by afeichuanqi** [comment]
> @ivpusic hey man, it's been months :)
> There is no issue on the regression at all for this library and i believe quite a number of people been using this fork without issue. Would love if you can consider this to be merged.
> 
> Something you might want to take note
> 
> I haven't remove the original `RSKImageCropper` library from the Podspec.
> This is because I want this fork to be accepted first. The effect is only a slightly larger build artifact.
> Once this fork merged to main repo, i will make another PR to completely remove the old dependency on `RSKImageCropper`

I still encountered this problem in the fork you just updated.

**Comment by sergioutama** [comment]
@afeichuanqi can you share your project detail
RN version, Xcode, etc ?

**Comment by afeichuanqi** [comment]
> @afeichuanqi can you share your project detail
> RN version, Xcode, etc ?
> And if possible setup a project where i can check and replicate the bugs you mentioned

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 5.30 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-26 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by afeichuanqi** [comment]
> @afeichuanqi can you share your project detail
> RN version, Xcode, etc ?
> And if possible setup a project where i can check and replicate the bugs you mentioned

The situation occurs when a separate cropping box is opened, such as directly calling ImagePicker.openCropper, the above warning message will occur, resulting in

**Comment by afeichuanqi** [comment]
> @afeichuanqi can you share your project detail
> RN version, Xcode, etc ?
> And if possible setup a project where i can check and replicate the bugs you mentioned

When I try to open the clipping box alone and the path is ph: // ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED / L0 / 001, it freezes

**Comment by sezginriggs** [comment]
@ivpusic I would like to suggest using TOCropViewController too and merging @sergioutama 's changes would be very good. I believe this is something most people needs.

**Comment by sezginriggs** [comment]
@sergioutama thank you very much for this modification. I switched to your repository for TOCropViewController and it works good but when I select a photo from camera roll (without resizing it) with openPicker and pass it to .openCropper() without setting height/width, result image becomes low quality. What might be the reason for that?

**Comment by sergioutama** [comment]
@sezginriggs most likely the regression issue (there was issue on this couple of months ago), on the iOS the core code to resize actually reduce the size 2x and default cropper image is 200x200 pixel, which is in today screen is very very small resulting in a bad and low quality image.

There is a work around above in this discussion how i overcome it, I recently sync with the master repo and not aware of the regression on image quality.

**Comment by sezginriggs** [comment]
@sergioutama master repo with RSKImageCropper seems working fine about this. Unfortunately setting 2x height/width doesn't change anything if you referring this as workaround.

**Comment by afeichuanqi** [comment]
> @afeichuanqi thanks that give me encouragement to work on this library once again

reports] Main Thread Checker: UI API called on a background thread: -[UIViewController init]

When you call ImagePicker.openCropper directly, you will find that the ui thread pauses for 4-5 seconds before you can continue the operation.
Can you take a look

**Comment by alexpchin** [comment]
What's going on with this PR? Do you need some support or will this be merged?

**Comment by sergioutama** [comment]
@alexpchin this PR was old so it became stale.
I just updated this so hopefully @ivpusic can look at this PR again and see whether we can move forward with this PR.

**Comment by ivpusic** [comment]
@sergioutama thanks a lot!

**Comment by ivpusic** [comment]
released https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.31.1

**Comment by sergioutama** [comment]
Thanks @ivpusic I thought I will do the cleanup in another PR after you merged this part of the code because the old library is still there, but i saw you cleaned up the old code. 👍 👍

**Comment by guy-shahine** [comment]
Thank you @sergioutama & @ivpusic highly appreciated. The switch came right in time

**Comment by sergiulucaci** [comment]
Great stuff @sergioutama! Is there any way to set by default the rectangle area as a **square** instead of choosing it from the action sheet?

**Comment by praveenbalajia** [comment]
Thank you @sergioutama, Great Fix for iOS cropping issue and very flexible cropping feature

**Pull request merged**
