### PR TITLE
Skip WRITE_EXTERNAL_STORAGE permission for Android 9 and newer

### PR DESCRIPTION
**Pull request by pranatha**

### CODE REVIEW

**Comment by arkadiyk** [comment]
WRITE_EXTERNAL_STORAGE permission needs to be removed from camera access as well

**Comment by manuelabarca** [comment]
Any reviewers for this ?

**Comment by ivpusic** [comment]
on android 23 it does not work

```
[Error: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/60 from pid=3558, uid=10061 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()]
```

**Comment by ivpusic** [comment]
commit here https://github.com/ivpusic/react-native-image-crop-picker/commit/2437d998acd0fe9582bea97fb1e048f79bb50c93. however we still need to add proper implementation for scoped storage for android 11

**Pull request closed without merging**
