### PR TITLE
Add Privacy manifest

### PR DESCRIPTION
**Pull request by ujeon**
Add Privacy Manifest for [File timestamp APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393), .creationDate & .modificationDate

### CODE REVIEW

**Comment by saraff13** [comment]
@ujeon Do we only need Photos and Videos to be defined? I tried adding this privacy file but it didn't worked.

**Comment by Maker-Mark** [comment]
This could close https://github.com/ivpusic/react-native-image-crop-picker/issues/2040 FYI

**Comment by ujeon** [comment]
@saraff13 

Are there any additional policies needed besides the Photo and Video policy? (just in my opinion, Apple make us somewhat confusing 🥲)

 I'm having trouble understanding why adding a Privacy file didn't work, but could you mean there's an issue with the PDF generated from the archive?

**Comment by saraff13** [comment]
> @saraff13
> 
> Are there any additional policies needed besides the Photo and Video policy? (just in my opinion, Apple make us somewhat confusing 🥲)
> 
> I'm having trouble understanding why adding a Privacy file didn't work, but could you mean there's an issue with the PDF generated from the archive?

1. In library setup we add NSPhotoLibraryUsageDescription, NSCameraUsageDescription, and NSMicrophoneUsageDescription. So we should add all privacy changes related to Photo, Video, and Audio as well.

Yes, privacy report generated from archieve is giving error related to TOCropViewController that is being used as a dependency inside of RNImageCropPicker.

**Comment by ujeon** [comment]
> > @saraff13
> > Are there any additional policies needed besides the Photo and Video policy? (just in my opinion, Apple make us somewhat confusing 🥲)
> > I'm having trouble understanding why adding a Privacy file didn't work, but could you mean there's an issue with the PDF generated from the archive?
> 
> 1. In library setup we add NSPhotoLibraryUsageDescription, NSCameraUsageDescription, and NSMicrophoneUsageDescription. So we should add all privacy changes related to Photo, Video, and Audio as well.
> 2. Yes, privacy report generated from archieve is giving error related to TOCropViewController that is being used as a dependency inside of RNImageCropPicker.



1. Do you have any reference for that? I have not recognized for that.

2. Thanks, I've set the minimum TOCropViewController version to [2.7.0](https://github.com/TimOliver/TOCropViewController/releases/tag/2.7.0), which supports the privacy manifest. However, there seems to be an issue with TOCropViewController's privacy manifest (or something else).. I will open issue for that on TOCropViewController

**Comment by saraff13** [comment]
> > > @saraff13
> > > Are there any additional policies needed besides the Photo and Video policy? (just in my opinion, Apple make us somewhat confusing 🥲)
> > > I'm having trouble understanding why adding a Privacy file didn't work, but could you mean there's an issue with the PDF generated from the archive?
> > 
> > 
> > 
> > 1. In library setup we add NSPhotoLibraryUsageDescription, NSCameraUsageDescription, and NSMicrophoneUsageDescription. So we should add all privacy changes related to Photo, Video, and Audio as well.
> > 2. Yes, privacy report generated from archieve is giving error related to TOCropViewController that is being used as a dependency inside of RNImageCropPicker.
> 
> 1. Do you have any reference for that? I have not recognized for that.
> 2. Thanks, I've set the minimum TOCropViewController version to [2.7.0](https://github.com/TimOliver/TOCropViewController/releases/tag/2.7.0), which supports the privacy manifest. However, there seems to be an issue with TOCropViewController's privacy manifest (or something else).. I will open issue for that on TOCropViewController

1. Sorry, I couldn't find any reference. I was just checking possibility of failures.
2. They have recently merged the fix in Privacy Manifest file. I think we will get a release soon. Once there is a release from TOCropViewController, This library will automatically pickup the latest version.

**Comment by saraff13** [comment]
@ujeon TOCropViewController version [2.7.3](https://github.com/TimOliver/TOCropViewController/releases/tag/2.7.3) is released.

**Comment by ujeon** [comment]
@saraff13 Thanks 👍 I did update min sdk to 2.7.3

> Sorry, I couldn't find any reference. I was just checking possibility of failures.

I have worked based on [required api scanner](https://github.com/Wooder/ios_17_required_reason_api_scanner?tab=readme-ov-file)'s "text-based scanner" and following the scanner's result, two required API `.creationDate` & `.modificationDate`. 

(it just my opinion) This library requires NSPhotoLibraryUsageDescription, NSCameraUsageDescription, and NSMicrophoneUsageDescription, but it does not mean required apis are used. so I think that adding privacy manifest for just `.creationDate` & `.modificationDate`

**Comment by Maker-Mark** [comment]
@ivpusic can we get this merged and released?

**Comment by mateusdegobi** [comment]
> @ivpusic can we get this merged and released?

please, I'm waiting for it

**Review by ivpusic — APPROVED** [review]

**Comment by ivpusic** [comment]
new version just relased. thanks for PR!

**Pull request merged**
