### PR TITLE
Update pod dependency to support rn 0.60

### PR DESCRIPTION
**Pull request by sunnylqm**
https://github.com/facebook/react-native/commit/2321b3fd7f666ce30f5dad4cd2673ddf22972056#diff-7538dfd5a1053e07f15cfe72274360caR10

### CODE REVIEW

**Comment by sunnylqm** [comment]
May need a major version bump

**Comment by sunnylqm** [comment]
And also need this one https://github.com/ivpusic/react-native-image-crop-picker/pull/962

**Comment by ivpusic** [comment]
tnx!

**Comment by oleksandr-dziuban** [comment]
@ivpusic Please publish new version on npm, thank you!

**Pull request merged**
