### PR TITLE
Added android equivalent code for skipping image compression.

### PR DESCRIPTION
**Pull request by Mikunj**
As discussed with @fubar, these changes are the android equivalent of those that were made for iOS.

**I haven't yet had time to test these changes.**

### CODE REVIEW

**Comment by ivpusic** [comment]
thanks!

**Comment by ivpusic** [comment]
could you please try it out with different settings and confirm that it works?

**Comment by Mikunj** [comment]
Yep, i'll get it tested by the end of the week 👍

**Comment by Mikunj** [comment]
Ok i have tested it with a GIF (300x 200) and DNG (2000 x 1000) file with the following settings:

```compressQuality: 0.8 ``` -> Converted to `jpeg`
```compressQuality: 0.8, compressMaxWidth: 100, compressMaxHeight: 100``` -> Converted to `jpeg`
```compressMaxWidth: 100, compressMaxHeight: 100``` + individually -> Converted to `jpeg`
```compressQuality: 1``` -> Only converted `DNG` to `jpeg`
```No settings set``` -> Only converted `DNG` to `jpeg`

**Comment by Mikunj** [comment]
@ivpusic i also fixed up a minor issue, do you want me to create a new PR?

**Comment by ivpusic** [comment]
@Mikunj tnx a lot! yes, please create another PR.

**Pull request merged**
