### PR TITLE
fix issue #184 add image mime type detection

### PR DESCRIPTION
**Pull request by DoTalkLily**
https://github.com/ivpusic/react-native-image-crop-picker/issues/184

### CODE REVIEW

**Comment by ivpusic** [comment]
thanks for PR. Feature is great, but I suggest to change one thing. We should not put mime type into options. Instead for every image we should extract mime type and convert it to png and jpg, depending on mime type. So in this case, we would do this in Compression.m. All code regarding storing mime type to options should be removed.

**Comment by DoTalkLily** [comment]
You're right. But one more thing, the function should be called with NSData, which I could got in :
[manager
                 requestImageDataForAsset:phAsset
                 options:options
                 resultHandler:^(NSData *imageData, NSString *dataUTI,
                                 UIImageOrientation orientation,
                                 NSDictionary *info) {
                     dispatch_async(dispatch_get_main_queue(), ^{
                         [indicatorView stopAnimating];
                         [overlayView removeFromSuperview];
                         [self processSingleImagePick:[UIImage imageWithData:imageData] withViewController:imagePickerController];
                     });
                 }];

Or I have to call UIImageJPEGRepresentation to get NSData to determine the mime type.
Any suggestions ?

Oh, I miss the function:
persistFile, where all tmp pic is stored with 'jpg' suffix.

**Comment by ivpusic** [comment]
we could try to extend compressImage method with `withMime` parameter, and then before passing try to figure out mime type. I don't know if this is possible with PHAsset, some investigation is needed here. Could you do that? Thanks

**Comment by DoTalkLily** [comment]
hi, in this callback function
 - (void)imageCropViewController:(RSKImageCropViewController *)controller
                   didCropImage:(UIImage *)croppedImage
                  usingCropRect:(CGRect)cropRect 
We got the UIImage ,I didn't find a way to get mime type or file path directly from UIImage. One workaround is to get NSData with UIImagePNGRepresentation then detect the type. (If use UIImageJPEGRepresentation the - (NSString *)mimeTypeForData:(NSData *)data  will be jpeg.)

image

**Comment by DoTalkLily** [comment]
An other way to make code neater is to use associated objects mechanism . We could store the mime type in UIImage as a feature of the image, it seems to be more appropriate. What you think?

**Comment by ivpusic** [comment]
I can see things will be starting more and more complicated to achieve the simple goal. Currently I don't see very clean way to implement detecting mime type detection for all our options. For now, I will close this PR.

Thanks a lot for your time and effort.

**Pull request closed without merging**
