### PR TITLE
support ios 8

### PR DESCRIPTION
**Pull request by luhui**

### CODE REVIEW

**Comment by ivpusic** [comment]
thanks

**Comment by ivpusic** [comment]
actually, I think it makes more sense to do this check from your application code. You will anyway have to specify `compressVideoPreset` from code. If your device does not support 4k, put some other, or do condition in your code.

**Comment by ivpusic** [comment]
update: PR reverted

**Comment by luhui** [comment]
Hi, the crash is in the `init` method of `Compression`, `AVAssetExportPreset3840x2160` is available 9.0 above.   
So check the system version in the `init` method is necessary

Here is definition in AVAssetExportSession.h
image

**Comment by ivpusic** [comment]
ahaa, then sorry, my bad, will merge it back

**Pull request merged**
