### PR TITLE
returned localIdentifier and filename in response

### PR DESCRIPTION
**Pull request by gameboyVito**
Reference on #384 

This PR adds two new response property: one is `localIdentifier`, the other is `filename`

### CODE REVIEW

**Comment by ivpusic** [comment]
thanks a lot!

**Comment by gameboyVito** [comment]
You are welcome

**Comment by kholiavko-roman** [comment]
Guys, now when I take photo from camera it does not return filename, how to get it ?

**Comment by ivpusic** [comment]
@gameboyVito could you help here?

**Comment by kholiavko-roman** [comment]
Now I see, that you edited readme, and filename was marked as ios only.  but how I can get filename on android ?

**Comment by ivpusic** [comment]
should be returned as part of url

**Pull request merged**
