### PR TITLE
Fix RSKImageCropper build failed

### LINKED ISSUE #281: RSKimageCropper issue
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.8
- react-native v0.42.0

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
run issue   xcode 8.2 has no problem ,when i run in # xcode 8.3 ,it make problem
 

### Actual behaviour
Redefinition of module 'RSKImageCropper'   issue

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

### PR DESCRIPTION
**Pull request by magrinj**
Fix #281

### CODE REVIEW

**Comment by ivpusic** [comment]
tnx!

**Comment by magrinj** [comment]
If you use cocoa pods and you try to build it in release mode, you're going to get a failed compilation, because you need to change this in you Podfile (until it will be released on cocoapods):
From
```
pod 'RSKImageCropper'
```
To
```
pod 'RSKImageCropper', :git => 'https://github.com/ruslanskorb/RSKImageCropper.git', :branch => 'master'
```

**Comment by amitbravo** [comment]
Do we have to re-run pod install for this ? what if I use always pod 'RSKImageCropper', :git => 'https://github.com/ruslanskorb/RSKImageCropper.git', :branch => 'master' from beginning ?

**Comment by magrinj** [comment]
If you are on a old version of RSKImageCropper or if the problem is not merged an deploy on this library you need to use the git repository in podfile :)

**Pull request merged**
