### PR TITLE
Add chooseText and cancelText properties

### PR DESCRIPTION
**Pull request by smsmdida**
added ability to change control buttons texts in crop

### CODE REVIEW

**Comment by ivpusic** [comment]
thanks for PR. Could you prefix properties with ‘cropper’ to have consistent naming with opet cropper related properties?

**Comment by smsmdida** [comment]
@ivpusic done

**Comment by pistonsky** [comment]
Will this be merged? We are making an app that supports multiple languages and this feature is a must. Please! @ivpusic

**Comment by ivpusic** [comment]
@pistonsky could you fix merge conflicts and I will then merge it?

**Comment by istro** [comment]
@ivpusic & @pistonsky - I just rebased it on master & opened a [separate PR](https://github.com/ivpusic/react-native-image-crop-picker/pull/699) - figured that would be quicker than reaching out to @smsmdida to ask him to rebase.

As a side note - thanks for great work!

**Comment by ivpusic** [comment]
tnx all. merged here https://github.com/ivpusic/react-native-image-crop-picker/pull/699

**Pull request closed without merging**
