### PR TITLE
Exif data extraction

### PR DESCRIPTION
**Pull request by nico1510**
Hi @ivpusic this is a pull request which adds exif data to the image response which some people (including me) asked for here https://github.com/ivpusic/react-native-image-crop-picker/issues/75.
Everything works for me but I'm a Java/JS dev so you should check the objective C code closely. Unfortunately I don't own an iPhone so I couldn't test if it also works when taking a picture with the camera (https://github.com/ivpusic/react-native-image-crop-picker/compare/master...nico1510:master#diff-c227004bfb2fcf3e01a87ae371a37a2dR159)

### CODE REVIEW

**Comment by pho3nixf1re** [comment]
Why was this PR closed? This seems to be an unresolved issue that is working in your fork.

**Comment by nico1510** [comment]
Even though this pull request was closed the code was merged at some point into master I think.

**Comment by pho3nixf1re** [comment]
I see that now. We are using a rather old version of this tool before this was merged in. Time to update a dependency!

**Comment by dancherb** [comment]
Exif data is working for me on Android but not on iOS, more info here: https://github.com/ivpusic/react-native-image-crop-picker/issues/751 - please could you have a look?

**Pull request closed without merging**
