### PR TITLE
Added an flag to the gallery intent to prevent two instances of it

### PR DESCRIPTION
**Pull request by svbutko**
Found a better solution to the issue which is described in [#581](https://github.com/ivpusic/react-native-image-crop-picker/pull/581). Hope this one is better than the previous attempt.

### CODE REVIEW

**Comment by shutnickwork** [comment]
I need this. Approve please.

**Comment by yanel777** [comment]
I need this too. Approve please.

**Comment by ivpusic** [comment]
thanks a lot!

**Comment by paintedbicycle** [comment]
This is happening on iOS as well.

img_0199

**Pull request merged**
