### PR TITLE
Make list items accessible

### PR DESCRIPTION
**Pull request by v-miibr**
We noticed that one of the views for selecting images was not accessible and would like to make it accessible. This was based on user feedback.

### CODE REVIEW

**Comment by shiweiwei114** [comment]
This is great! Currently the user is not able to select any photos in accessibility mode (VoiceOver), we need this! :)

**Comment by FrozenIce0617** [comment]
You saved my day, @v-miibr 
It would be great if we can merge this change asap.

**Comment by marcshilling** [comment]
You should also add:
`cell.accessibilityTraits = UIAccessibilityTraitImage | UIAccessibilityTraitButton;`

This will make it clear that it's an image that can be selected, and iOS will even sometimes be able to detect the contents of the image and read a description...super cool.

I'm using this patch and it's been working great. Should definitely be merged in with my suggested change!

**Comment by pnikhilp** [comment]
Any update on when will be this change available in the package?

**Comment by jan-happy** [comment]
This would be super helpful for a lot of people, please consider merging this!

**Review by Nanjundan — APPROVED** [review]

**Comment by Nanjundan** [comment]
Hello @ivpusic Can you consider merging this PR with AccessibilityTraits?

**Pull request merged**
