### PR TITLE
#177 Update build.gradle to reference node_modules for react-native dependency

### PR DESCRIPTION
**Pull request by TigerC10**

### CODE REVIEW

**Comment by ivpusic** [comment]
hm, could you explain why this change?

**Comment by TigerC10** [comment]
It was discussed in #177 but the gist of it is that in the build.gradle file you specify a dependency on the latest version of `com.facebook.react:react-native`.  This dependency is satisfied through maven.

If someone has downloaded react-native and built it themselves before including this project, their local .m2 cache will have an appropriate version of react-native.

However, if you haven't done that separate step before it'll attempt to download react-native from maven central.  Facebook stopped pushing updates to maven central, the latest version in that maven repo is `0.20.1` which does not have the requisite library `com.facebook.react.modules.core.PermissionListener`.

Now, the consuming projects out there that leverage react-native-image-crop-picker could possibly configure the gradle build to make sure that react-native compiles first and feed that into react-native-image-crop-picker's build phase...  But it would add some extra configuration to the installation steps and doesn't really fix Android Studio's tendency to move react-native-image-crop-picker build before the react-native build when "upgrading" gradle files.

A more resilient solution is to add the local copy of react-native from the `node_modules` directory as a maven repository.  This also guarantees that you won't ever use a mis-matched version of react-native to build react-native-image-crop-picker, it'll always use the version installed in the project by `npm`.

**Comment by TigerC10** [comment]
@ivpusic - can you think of an alternate fix?

**Comment by TigerC10** [comment]
@ivpusic any updates?

**Comment by sibelius** [comment]
I don't think this is needed for this package?

**Comment by TigerC10** [comment]
It's pretty common for react-native modules that depend on a specific version of react-native in android redefine the repositories such that the RN android dependency checks inside the node_modules directory.  Check https://github.com/facebook/react-native/issues/12309 for the details.

Here are some other projects doing it:
https://github.com/airbnb/react-native-maps/blob/master/build.gradle
https://github.com/devfd/react-native-google-signin/blob/master/android/build.gradle
https://github.com/Nodonisko/react-native-twilio/blob/develop/android/build.gradle


Though, another method of achieving this might be to use [react.gradle](https://github.com/facebook/react-native/blob/master/react.gradle) instead:
```
apply from: "../../node_modules/react-native/react.gradle"
```

**Comment by Palisand** [comment]
@TigerC10 I'm having the same issue with [react-native-image-picker](https://github.com/react-community/react-native-image-picker/blob/develop/android/build.gradle) after building RN from source. I haven't been able to get it working; care to lend a hand?

**Comment by Palisand** [comment]
@sibelius You're probably right about this PR not being necessary. After experiencing the same android build failure issues with react-native-image-picker and react-native-maps, I found [this solution](https://github.com/airbnb/react-native-maps/issues/1309#issuecomment-323689000).

If you're building RN from source and come across this issue, updating your app's _`android/build.gradle`_ with the following should do the trick:
```
allprojects {
    // ...
    configurations.all {
        resolutionStrategy {
            dependencySubstitution {
                substitute module('com.facebook.react:react-native') with project(':ReactAndroid')
            }
        }
    }
}
```
Credit: @madox2

**Comment by ivpusic** [comment]
closing it at this is not necessary

**Comment by subooom** [comment]
`project :ReactAndroid not found.`
After copy pasting this:

     configurations.all {
        resolutionStrategy {
            dependencySubstitution {
                substitute module('com.facebook.react:react-native') with project(':ReactAndroid')
            }
        }
    }

**Comment by devotebest** [comment]
I got same project :ReactAndroid not found.

**Pull request closed without merging**
