### PR TITLE
added minFiles option, and a new response called sourceURL

### PR DESCRIPTION
**Pull request by gameboyVito**
reference #395 

- added a new option: `minFiles`
- added a new response property: `sourceURL`
- updated README

### CODE REVIEW

**Comment by ivpusic** [comment]
thanks a lot!

**Comment by ivpusic** [comment]
just one question...do we need to add something like https://github.com/ivpusic/react-native-image-crop-picker/blob/master/ios/ImageCropPicker.m#L399. Bug was reported some days ago because in case if key value was empty, app was crashing. Reference https://github.com/ivpusic/react-native-image-crop-picker/pull/397

**Comment by gameboyVito** [comment]
I guess it is because the app is running below ios8, which does not support PhotoKit. Yes, I think it is needed to check whether it is empty.

**Comment by ivpusic** [comment]
do you have 5min to add quick push?

**Comment by gameboyVito** [comment]
Sure

**Comment by gameboyVito** [comment]
I think this #397 has already fixed this issue.

**Comment by ivpusic** [comment]
but not for newly added `sourceURL` property. Or this one cannot be empty?

**Comment by gameboyVito** [comment]
Okay, I get it. Fixed - #408

**Pull request merged**
