### PR TITLE
Enable the ability to record video when launching the camera

### PR DESCRIPTION
**Pull request by tomSawkins**
Currently you are not able to record video when launching the camera. When you supply openCamera with mediaType "video" you are only able to take a picture.

This pr implements this functionality so you are able to call openCamera like below and get the recorded video returned:
`ImagePicker.openCamera({
  mediaType: "video"
}).then(video => {
  console.log(video);
});`

I've also fixed a bug with the dimensions (width, height) that are being returned for videos selected from the gallery in iOS being incorrect. In order to get the correct dimensions we need to apply `CGSizeApplyAffineTransform` to the video track `naturalSize` using `preferredTransform` from the same track.

### CODE REVIEW

**Comment by clmntcrl** [comment]
Any chance to see this PR merged soon ?

**Comment by NitroGhost** [comment]
@ivpusic any progress on this? or is #729 more desirable?

**Comment by shubham1164** [comment]
Any help on this? I am unable to record video from camera on Android. Not sure about IOS

**Comment by shubham1164** [comment]
Hi @clmntcrl, Thanks for reply. I need some more help in the github part. What is the meaning of #700  in the **ivpusic/react-native-image-crop-picker#700/head**?

It doesn't seems to be the commit hash code?

**Comment by shubham1164** [comment]
IOS app is crashing with this #700/head - image picker and video picker. Please verify

**Comment by clmntcrl** [comment]
I have no crash using the following request object (RN 0.55, iOS 12):

```js
const videoPickerRequest = {
    mediaType: "video",
    writeTempFile: false,
    compressVideoPreset: "HighestQuality",
}
```

I hope this will help you.

**Comment by ivpusic** [comment]
feature available in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.22.0

**Comment by tmjordan** [comment]
Hi, thanks for your great work. I installed the latest release, but i'm still not able to record videos. Should i do something more ??

**Pull request closed without merging**
