### PR TITLE
Update to AndroidX

### PR DESCRIPTION
**Pull request by rafcontreras**

### CODE REVIEW

**Comment by ovy9086** [comment]
why don't you squash this commits ? what's the point of having 3 commits that are later just being reverted 🤷‍♂️

**Comment by RichardLindhout** [comment]
@ovy9086 What is your point? He is probably using the inline edit tool from Github so you don't have to manually add a branch etc.

**Comment by Saad-Bashar** [comment]
When can we have the support for androidx?

**Comment by Saad-Bashar** [comment]
+1

**Comment by se-bastiaan** [comment]
These changes are nice, but for the package to be completely AndroidX compatible the ucrop dependency should be updated: https://github.com/Yalantis/uCrop/pull/538

**Comment by ivpusic** [comment]
released in 0.25.0

**Pull request closed without merging**
