### PR TITLE
Fix for adding files more than 30 at once for iOS

### PR DESCRIPTION
**Pull request by ZmicierBiesau**
I have getting crashes with selecting >30 images at once some times on iOS. I noticed that the less free memory you have, the more chance to get the crash you have.

### CODE REVIEW

**Comment by ivpusic** [comment]
thanks. maybe we need the same for video block?

**Comment by ZmicierBiesau** [comment]
Just checked video. Looks like all is ok with video. I think with images problems were caused by UIImage objects memory managing and there is no such problems with video, because video is processing in another way.

**Comment by ivpusic** [comment]
thanks a lot for help!

**Comment by ZmicierBiesau** [comment]
you are welcome

**Pull request merged**
