### PR TITLE
Add base64 data in result 

### PR DESCRIPTION
**Pull request by magrinj**
Add the base64 image data, in the response returned

### CODE REVIEW

**Comment by ivpusic** [comment]
hmm...is there really good use-case for this? Usually when you pick image you want to show it to the user, what you can right now, or you want to upload it to the server, what you can right now. What is your use case for introducing base64?

**Comment by ivpusic** [comment]
when you get filepath you can (optionally) read base64 with https://github.com/johanneslumpe/react-native-fs.

**Comment by magrinj** [comment]
@ivpusic With react-native you can set a picture with base64 datas, this case is a special case when some user want to send datas to server just after the image is selected. I think it's an enhancement for your library and lot of people can be in this case.

Base64 datas can also be used with `AsynStorage` to save a picture locally.

I try to use `react-native-fs` but that's doesn't work on my project, and I don't really want to use a big library just to get datas that are already get on the native side.

**Comment by ivpusic** [comment]
my concern are memory issues on android devices. I already had issue with decoding bitmap (https://github.com/ivpusic/react-native-image-crop-picker/blob/master/android/src/main/java/com/reactnative/picker/PickerModule.java#L110). I think by default we should not send base64, because for most use cases you don't need it, and you will waste phone memory.

I suggest that if we want to support this feature, to make it optional. So when selecting image if user wants to get base64, it should provide flag `includeBase64: true` to `openPicker` method.

What do you think? If you agree, can you update your PR to make this feature optional?

**Comment by magrinj** [comment]
I update my PR with the includeBase64 option as you suggest, I use `NSMutableDictionnary` for the `iOS` side, I don't really use objective-C often, so if you think there is a better solution just let me know.

**Comment by ivpusic** [comment]
thanks. I did some small changes and now it is merged. Will release new version

**Comment by ivpusic** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.5.5

**Comment by magrinj** [comment]
Thanks for your merge and your change!

**Pull request merged**
