### PR TITLE
Podspec file added for project.

### PR DESCRIPTION
**Pull request by gauravds**

### CODE REVIEW

**Comment by wasedaigo** [comment]
This seems to be a good addition. Since ReactNative 0.51.0 we can take advantage of this
https://github.com/facebook/react-native/commit/74146cb3158273921b768c97f229695e680ea82d

**Comment by heyjared** [comment]
Would love to see this merged. Had to downgrade to 0.15.3 recently as that was the last version with a podspec.

Was unable to manually link correctly when I had React specified as a pod.

**Comment by reedyrm** [comment]
I think this pull request is important if anyone wants to start running their react-native build thru a CI system.  So, I'd like to see the spirit of this pull request (podspec) incorporated into master.  Obviously this pull request is out of date, but wouldnt be hard to incorporate the concepts.

**Comment by gauravds** [comment]
@reedyrm  I'm updating it.

**Comment by hammadzz** [comment]
@gauravds is there a way I can help? I haven't added a pod spec before but I could figure it out. This is breaking my CI.

**Comment by ivpusic** [comment]
added in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.20.0

**Pull request closed without merging**
