### PR TITLE
Return cropped image rectangle

### PR DESCRIPTION
**Pull request by vanyaland**
Hey, @ivpusic! Please review.

## Summary

- Add `cropRect` response object
- `cropRect` is an Object typeof `CropRect`
- Use latest uCrop version `2.2.1` with the [ability](https://github.com/Yalantis/uCrop/issues/285) to get cropped image offset coordinates

#### Response example:

```javascript
...
cropRect: {
   x: 268,
   y: 0,
   width: 393,
   height: 393
}
...
```

#### Closes: #457

### CODE REVIEW

**Comment by ivpusic** [comment]
thanks a lot for implementing this feature. I was pretty busy to review it before. I see that there are now some merge conflicts. Do you have some time to take a look, fix merge conflicts, and then I will merge it. Thanks

**Comment by vanyaland** [comment]
@ivpusic, It's rebased.
You can review and merge if acceptable.

Thanks!

**Comment by vanyaland** [comment]
ping @ivpusic

**Comment by vanyaland** [comment]
ping @ivpusic

**Comment by ivpusic** [comment]
thanks a lot! sorry for being late for merge

**Pull request merged**
