### PR TITLE
Update ImageCropPicker.m

### PR DESCRIPTION
**Pull request by BlindDev**
Fixed issue #1225
https://github.com/ivpusic/react-native-image-crop-picker/issues/1225

### CODE REVIEW

**Comment by alimek** [comment]
yes, works for me too, thanks for fixing ;-) package-patched until published in NPM

**Review by ivpusic — APPROVED** [review]

**Comment by justinbhopper** [comment]
@ivpusic Just checking on the status of npm publish for this latest merged item?

**Comment by kowshik-sundararajan** [comment]
Hey @ivpusic, just wondering when the next release of this package will be and whether this merged fix will be included?

**Comment by broksonic21** [comment]
Do you have an ETA for when this will be pushed to npm?

**Comment by ivpusic** [comment]
just published new version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.35.2

**Pull request merged**
