### PR TITLE
Add more color options in RN Image crop picker

### PR DESCRIPTION
**Pull request by sahil290791**
Now we can specify **Toolbar**, **Statusbar** and **active-widget** color. If not specified it defaults to default colors.

### CODE REVIEW

**Comment by ivpusic** [comment]
tnx for PR. I think there is one mistake in updated readme file. `cropperActiveWidgetColor` is missing

**Comment by sahil290791** [comment]
@ivpusic I kept same name for `cropperActiveWidgetColor` => `cropperTintColor` as this if remove this option it will cause the problem to users who are already using this plugin.

**Comment by ivpusic** [comment]
sure, but you are not reading `cropperTintColor` anymore (https://github.com/ivpusic/react-native-image-crop-picker/pull/335/files#diff-b63ce3ce1e5c477c1141d6db752515d6L115), so it should not be in the readme. I suggest to remove `cropperTintColor` from readme as it is not used anymore in the code (I will write down breaking change), and document `cropperActiveWidgetColor` in the readme file.

**Comment by sahil290791** [comment]
Sure, will update the code.

**Comment by sahil290791** [comment]
@ivpusic Have replaced `cropperTintColor` with `cropperActiveWidgetColor`.

**Comment by ivpusic** [comment]
thanks

**Pull request merged**
