### PR TITLE
Enhancement:: Add: Filename in response object for Android

### PR DESCRIPTION
**Pull request by AmeyShrivastava**
Resolves: https://github.com/ivpusic/react-native-image-crop-picker/issues/1078

### CODE REVIEW

**Comment by krmao** [comment]
it's just a copy random name?  different names with the file selected

**Review by mirox99 — APPROVED** [review]

**Comment by maksymhcode-care** [comment]
Why is this not merged yet?

**Comment by harishgupta01** [comment]
Hi @ivpusic - Could you please let us know when we are planning to merge this PR ? This is a real blocker for me.

**Comment by inkCrazy** [comment]
image

{ modificationDate: '1736578903080',
  size: 176461,
  mime: 'image/jpeg',
  height: 4096,
  width: 3072,
  filename: '1736578903069.jpg',
  path: 'file:///storage/emulated/0/Android/data/com.hnao.znkq/files/Pictures/539d0371-c37c-47a7-8185-0301322dafb8.jpg' }
  与原始图片名字不一致

**Comment by gkasireddy202** [comment]
Getting the below error when I try to use the pod install.
react-native-image-crop-picker": "^0.41.6",
react-native:0.73.7
react:18.2.0

**Pull request merged**
