### PR TITLE
add support to uCrop setCircleDimmedLayer()

### PR DESCRIPTION
**Pull request by esganzerla**
set the setCircleDimmedLayer to "cropperCircleOverlay" option on react-native.

### CODE REVIEW

**Comment by ivpusic** [comment]
Thanks for PR. could you do the same for ios?

**Comment by esganzerla** [comment]
Cool. I just included the same property for iOS.

**Comment by ivpusic** [comment]
Awesome. Thanks!

**Comment by WillyRamirez** [comment]
Hi guys, thanks for this awesome feature. Question: does this provide only a circular overlay during cropping, or will the image also be cropped in a circle? So far with cropperCircleOverlay set to true, im still getting square images. Thanks in advance!

**Pull request merged**
