### PR TITLE
fix orientation (iOS)

### PR DESCRIPTION
**Pull request by TZXZ**
fix orientation(iOS)

### CODE REVIEW

**Comment by TZXZ** [comment]
@ivpusic

**Comment by ivpusic** [comment]
could you give me more details about this change? tnx

**Comment by TZXZ** [comment]
Hi, you can see this
[http://stackoverflow.com/questions/8915630/ios-uiimageview-how-to-handle-uiimage-image-orientation](url)
in my project, if I don't add those code, the picture will turn 90°. @ivpusic

**Comment by TZXZ** [comment]
this can fix it
[https://github.com/ivpusic/react-native-image-crop-picker/issues/175](url)

**Comment by ivpusic** [comment]
thanks!

**Pull request merged**
