### PR TITLE
Fix handling of deleted photos on iOS

### LINKED ISSUE #1251: NSInternalInconsistencyException attempt to delete and reload the same index path
### Version
- react-native-image-crop-picker v0.27.0
- react-native v0.61.4

### Platform
- iOS

### Expected behaviour
- Don't attempt to get deleted images from gallery

### Actual behaviour
- App crash at `react-native-image-crop-picker/ios/QBImagePicker/QBImagePicker/QBAssetsViewController.m:401`

### Steps to reproduce

1. Open `react-native-image-crop-picker` by calling `ImagePicker.openPicker` with `multiple` selection activated and just select some images from your gallery. Don't close the gallery.

2. Close your app and open Photos App and completely delete the photos you selected. Be sure delete from deleted folder. 

3. Go back to your app and you will see that the photos that you deleted disappear but counter says that you have some photos selected. Then select some other photos and finish the selection by tapping OK. 

4.- Boom!

### Attachments

- `__48-[QBAssetsViewController photoLibraryDidChange:]_block_invoke node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePicker/QBAssetsViewController.m:401`

Crash log file => [crash.log](https://github.com/ivpusic/react-native-image-crop-picker/files/4321363/crash.log)

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

### PR DESCRIPTION
**Pull request by brsaylor2**
See commit messages for details.

Fixes #1251

### CODE REVIEW

**Comment by brsaylor2** [comment]
FWIW, I've tested these changes against v0.37.2 and they still work correctly.

**Comment by ariiyu** [comment]
@ivpusic @brsaylor2 
This fix with react-native-image-crop-picker v0.38.0 works well. With this fix the issue is not reproduced on iOS 15.5.
(I also tested on iOS 14.5 and iOS 16.0 but the issue itself could not be reproduced in my environment.)
I tested it with RN v0.70.5, in my project.

**Comment by tomgreco** [comment]
@ivpusic I've tested this as well.
Works, please merge.

**Comment by charlyBerthet** [comment]
@ivpusic tested against v0.40.1 & RNv0.72.4. It works well, I will patch my local lib for release with this patch

**Pull request merged**
